[parity]
chain = "demo-spec.json"
base_path = "parity2"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8181
[websockets]
port = 8457
[account]
password = ["node.pwds"]
[mining]
engine_signer = "0x007ED29e106DB66552a927840F6D6B05a5D9C5F2"
reseal_on_txs = "none"
